### ISSUE TITLE
LaTeX macros do not execute in preview

### ISSUE THREAD

**Issue by i-thot-u-wanted2dance** [gpoore/codebraid-preview-vscode#10]
[LaTeX macros](https://pandoc.org/MANUAL.html#latex-macros) defined within my markdown file do not execute when the preview is displayed.  However they behave correctly when using a different pandoc-based preview extension for VSCode, namely [Pandoc Markdown](https://github.com/rwildcat/vsc-pandoc-markdown).  Can you show a simple example where this works correctly?

![Screenshot 2022-07-25 094458](https://user-images.githubusercontent.com/95660452/180792479-fab117de-7511-4012-be51-ce1dbd406552.png)

**Comment by gpoore** [comment]
There are a few different things happening here.

Fundamentally, this is due to format differences:
* The other extension treats the document as Pandoc's `markdown` format, which automatically uses Pandoc's `latex_macros` extension to expand custom LaTeX macros *before* they are passed on for HTML conversion. So in the other extension, the HTML literally contains `\langle a, b, c\rangle` and the `\tuple` definition never appears.
* This extension treats the document as Pandoc's `commonmark_x` format by default, which is why scroll sync works. `commonmark_x` doesn't support `latex_macros`, so `\tuple` actually appears in the HTML and needs to be defined. However, Pandoc discards all non-math LaTeX when generating HTML, so `\tuple` never gets defined.

One option is to change the input format to `markdown` in the extension settings (`codebraid.preview.pandoc.fromFormat`). If you do this, you will lose scroll sync. You would probably also want to disable the `Show Raw` option, which shows content in the preview that Pandoc ignores for HTML output but is used in generating other formats.

Another option is to modify the document to work with `commonmark_x`. If you define `\tuple` in math mode, like `$\newcommand{\tuple}[1]{\langle #1\rangle}$`, then the definition does get passed along to HTML, because now it is LaTeX math. However, the definition is local, so it isn't available elsewhere. To work around that, you need a global definition, either something like
```
$$
\newcommand{\tuple}[1]{\langle #1\rangle}
\global\let\tuple\tuple
$$
```
or alternatively `$\gdef\tuple#1{\langle #1\rangle}$`.

**Comment by i-thot-u-wanted2dance** [comment]
Thanks for the extremely helpful (and quick) response!  

Other (potential) users might find it helpful for the `codebraid-preview-vscode` documentation to:

- link directly to the section of the `pandoc` repo's wiki specifically about the state of the [relationship between `commonmark` and various extensions](https://github.com/jgm/pandoc/wiki/Roadmap#pandocs-markdown-transition-to-commonmark), and 
- include an example like the one worked through in this issue.  Many writers of technical documents are used to writing in `markdown` and then exporting via `pandoc` but are much less familiar with the specifics of the relationship between `commonmark_x` and `pandoc`.  They might appreciate more explicit help to take advantage of your package's powerful features (including scroll sync)!

**Comment by gpoore** [comment]
I've added more details about `commonmark_x` along with examples and links to the README.
