### ISSUE TITLE
Codebraid doesn't understand @tarleb's Lua filter `list-table` because of container without point (even if with point)

### ISSUE THREAD

**Issue by gusbemacbe** [gpoore/codebraid-preview-vscode#12]
Hello!

You can check the Lua file at @tarleb's [list-table](https://github.com/pandoc/lua-filters/tree/master/list-table). Codebraid doesn't understand that Lua filter because Codebraid accepts only the container with point. 

Observe that I modified the Lua filter, adding a point for `list-table` as Codebraid, but it gave the same error too.

Here is the screenshot:

![image](https://user-images.githubusercontent.com/2257024/184520953-075019b8-6fd9-418a-a340-27611ac46986.png)

I tested with the command `pandoc -s "List of supported languages in three syntax highlighters.md" -o result.html -f commonmark_x -t html5 -L filters/lua/list-table.lua` on terminal. Pandoc understood the Lua filter and generated without error:

![image](https://user-images.githubusercontent.com/2257024/184521236-78fd6a4a-8f11-4748-a8e8-b21f4f0fcdd9.png)

**Comment by tarleb** [comment]
Thank you for crediting my work on Lua filters. This specific filter was written by @not-my-profile, I only help to maintain it.

(Apologies for this off-topic comment, I just want to make sure that contributors get the recognition they deserve for their work. :relaxed: )

**Comment by gpoore** [comment]
The sourcepos extension which Codebraid Preview uses for scroll sync will
insert Div nodes into the AST with a data-pos attribute. This is probably
the issue, since the list-table filter isn't expecting these.

I'd suggest using a filter to discard all Div nodes with a data-pos
attribute that are inside of a list-table Div (or replace them with Null
nodes). Then use the list-table filter as normal. Or there might be a way
to customize the list-table filter to work around these nodes.
