### ISSUE TITLE
Change font using my own stylesheet

### ISSUE THREAD

**Issue by fhill2** [gpoore/codebraid-preview-vscode#14]
I am trying to set the previewer to show a font different to the font i am using in vscode?

Is this possible? Maybe Im missing something..

### 1 - adding pandoc arg `--css`  in vscode settings.json

```json  
"codebraid.preview.pandoc.options": [
        "--css assets/css/theme.css"
    ]
```

### 2 - Adding css: to _codebrain_preview.yml

```yaml
#  _codebrain_preview.yml
css: assets/css/theme.css
``` 

___
CSS:
```css 
body {
  font-family: 'Liberation Serif';
}
```

I know its working using only pandoc with this test:

```bash
pandoc --defaults _codebraid_preview.yml -o market-research.html market-research.md
# this outputs an html with font as 'Liberation Serif'
```

___

Removing [--css flags](https://github.com/gpoore/codebraid-preview-vscode/blob/9f212fee387298f304c4eb25decd74024e39bd39/src/preview_panel.ts#L229) from `this.pandocPreviewArgs` does enable my custom font from the stylesheet.

**Comment by gpoore** [comment]
The issue is that currently the preview adds all of its settings after user settings, to prevent critical preview settings from being overwritten. But then your CSS is before the preview CSS, so it is overwritten.

Settings will need to be reorganized so that all critical preview settings are still added after user settings, but things like CSS are handled in reverse order. Most of that should be straightforward, at least for CSS, so there should be a new release soon with a fix.

**Comment by gpoore** [comment]
This should work correctly now by default with the latest release. There are two new settings that determine whether the default CSS is loaded and whether it has precedence: `codebraid.preview.css.useDefault` and
  `codebraid.preview.css.overrideDefault`.
