### ISSUE TITLE
Previewing Local Images

### ISSUE THREAD

**Issue by jdc136** [gpoore/codebraid-preview-vscode#15]
Hi, I couldn't get local images to render using your extension.

I reviewed issue #13 including [this comment](https://github.com/gpoore/codebraid-preview-vscode/issues/13#issuecomment-1295895770) which mentions "you may be using a different directory structure or something else may be interfering". I am not sure what would be interfering. 

The file for which I want to insert an image is located in a directory structure like this: `~\Documentation\resources\file.md`. The image I am linking is located here: `~\Documentation\images\image.jpg`. In the markdown, I reference the image like this: `![alt](../images/image.jpg`.

I am not sure what to change in order to get this to work. I am unfamiliar with the Webview API - any direction you could provide would be greatly appreciated!

**Comment by gpoore** [comment]
This is probably the Content Security Policy again, just in a different form, due to the image being under a different directory than the Markdown file. The next release will permit more by default, and will also provide options for modifying the Content Security Policy. But it will be at least a few days until the next version is out.

**Comment by jdc136** [comment]
Gotcha, no worries, I'll keep my eye out for the next update. Thank you for this tool, overall it's a great supplement to VS Code and Pandoc!

**Comment by gpoore** [comment]
The issue here is permissions to access local resources outside the document directory (outside `~\Documentation\resources\`).

I've just released v0.11.0, which includes two ways to address this:
* If you open `~\Documentation` as a workspace, then all files within it will automatically be accessible for the preview.
* You can also now set specific locations to always be accessible, regardless of the document or workspace. So you could add `~\Documentation\images` to the new setting `codebraid.preview.security.extraLocalResourceRoots`.
