### ISSUE TITLE
More control over pandoc and lua environment

### ISSUE THREAD

**Issue by wlupton** [gpoore/codebraid-preview-vscode#17]
Ever since the recent [pandoc-discuss announcement](https://groups.google.com/g/pandoc-discuss/c/drXv16dnhnE/m/2XSi0PZOAQAJ?utm_medium=email&utm_source=footer), I've been meaning to try out Codebraid, and it's great!

I'd like to be able to make it easy for others to run pandoc, together with a quite extensive set of customisations. All the customisations are available in a "data-dir" tree that people can check out from git. I also need to set the lua path so some utilities can be found. Therefore, it would be wonderful to be able to:

* Set `data-dir` (ideally allowing the definition to reference an environment variable, as in `data-dir: ${PANDOCDIR}`)
* Set `LUA_PATH` (if environment variables can be referenced, then static `LUA_PATH="${PANDOCDIR}/?.lua;;"` might be sufficient)
* Search for the defaults file (`_codebraid_preview.yaml` or another file) in the `data-dir` tree (in `data-dir` `/defaults` by convention)

Also, some of my lua filters aren't working as expected, so it would be great to be able capture the pandoc `stdout` and `stderr`  output. Could they perhaps be made available via the `OUTPUT` tab (or elsewhere)?

Note: My filters access files within the data-dir tree, so I wondered whether I was hitting a security issue. I tried setting `Codebraid › Preview › Security: Extra Local Resource Roots` to the data-dir root (I assume that this is a colon-separated list?) but it didn't seem to make a difference. Ideally this setting might also be able to reference an environment variable (perhaps it already can).

**Comment by gpoore** [comment]
There are a couple of different ways you should be able to work with `data-dir` currently:
* In `settings.json`, under `codebraid.preview.pandoc.build`, under `*.md`, under `preview.html.options`, you could add an entry `--data-dir ${PANDOCDIR}`. `options` are passed to a shell, so environment variables should work.
* In `_codebraid_preview.yaml`, you could set `data-dir`, and that should interpolate environment variables since it is just a special defaults file.

If these don't let you do what you need with `data-dir`, let me know what capabilities are missing.

Once `data-dir` is set, you should be able to specify `defaults` in `_codebraid_preview.yaml` or in the Codebraid Preview settings to use defaults files located there. `_codebraid_preview.yaml` itself is required to be in the same directory as the document file(s), but if it sets `defaults`, then `data-dir` is searched for those. `_codebraid_preview.yaml` is just a Pandoc defaults file, so all usual features apply.

For `LUA_PATH`, it would be possible to add a setting within Codebraid Preview to allow environment variables to be specified for the child process running Pandoc. However, depending on what you are doing, you may already be able to accomplish this within the filters themselves. Following https://pandoc.org/lua-filters.html, I've used `PANDOC_SCRIPT_FILE` combined with `pandoc.path.directory` and `pandoc.path.join` to have a Lua script import other Lua scripts located in relative directories. Examples are in `codebraid-preview-vscode/pandoc/readers`.

There is currently some minimal logging under `OUTPUT`, `Codebraid Preview` and I can look into expanding that to provide more information. The preview displays Pandoc stdout (the HTML preview is sent to stdout), unless there is an error, in which case it displays Pandoc stderr verbatim. Additional logging could provide a little more information, but the preview should already be displaying everything that's available, except when they are warnings written to stderr. Depending on what your filters are doing, you might try `io.stderr:write(...)` and then `os.exit(1)` to do some print debugging with the preview open. Another possibility is that your filters are having issues due to the `sourcepos` data for scroll sync. See `README`, `A note on filters` for that.

**Comment by wlupton** [comment]
Thanks very much for the detailed response, which was incredibly helpful. I'm feeling a bit bad because I don't think that I had read the documentation as closely as I could/should have done :(.

* **Data dir**: Actually I'd already set this in the defaults file, so I'm not quite sure why I mentioned it. Perhaps I was wondering whether it could be given "first-class" treatment, but this doesn't seem necessary

* **Defaults files**: Thanks for suggesting the use of `defaults` within the defaults file. I've changed things so there's a central `$PANDOCDIR/defaults/codebraid-defaults.yaml` and local `_codebraid_defaults.yaml` files that reference it. Much better!

* **LUA_PATH**: Thanks for the suggestions. I'm motivated to get rid of it!

* **Logging**: Thanks for `os.exit(1)` tip. I've created a simple `trigger-error.lua` filter that can be enabled in the local `_codebraid_defaults.yaml` as needed

There are a couple of other things that I need to look into:

* **CSS**: I've got some local CSS that's referenced (via full paths) in the defaults file, but doesn't seem to show up in the preview. I've played with some of the CSS settings but that doesn't seem to be the problem. I can investigate further but just wondered whether there's anything obvious

* **Spans and divs**: Yes I will need to work around the `sourcepos`-emulation spans and divs. For example one of my filters checked for a three-element `Str`, `Space`, `Str` paragraph but now it's a `Span`, `Space`, `Span` paragraph. Not a problem (Note: I've changed the `*.md` reader from `commonmark_x` to `markdown`, probably temporarily)

**Comment by wlupton** [comment]
Oh there was one other thing. Is it possible to control which pandoc binary is used?

**Comment by gpoore** [comment]
* **CSS:** If the CSS files are in the same directory as the document, or a subdirectory, check the setting `codebraid.preview.security.allowLocalStyles` (should be `true` by default). If the CSS files are elsewhere, then modify the setting `codebraid.preview.security.extraLocalResourceRoots` to add additional locations that the preview can access. Note about security permissions: These determine what the preview can access, since it is capable of runing JavaScript etc. The security settings don't affect what Pandoc itself can access.
* **Pandoc binary:** There isn't a setting for this, but I've been thinking about adding one, so I'll go ahead and do that in the next release.

**Comment by wlupton** [comment]
Thanks again. My CSS is working now (it was my fault). I see that extra resource roots can't use environment variables (or at least not of the form `${var}`) so I wonder whether in fact it _would_ be justified to add a setting for pandoc `data-dir` that:
* Supports being set via an environment variable
* Is automatically set as an extra resource root
* Is defaulted per the pandoc rules

The first bullet point (environment variable) is perhaps not vital if this is the only place that it needs to be set (but it would still be nice).

**Comment by gpoore** [comment]
The latest release adds several settings that should be helpful. Here's the relevant part of the change log:

> * Added setting `codebraid.preview.pandoc.executable`.  This allows
>   customizing the location of the Pandoc executable, or using a wrapper
>   script.
> 
> * Added setting `codebraid.preview.pandoc.extraEnv`.  This allows
>   setting additional environment variables for the Pandoc subprocess.
> 
> * Added setting `codebraid.preview.pandoc.showStderr`.  This allows the
>   preview to display a notification when Pandoc completes without errors, but
>   stderr is non-empty.
> 
> * Added setting
>   `codebraid.preview.security.pandocDefaultDataDirIsResourceRoot`.
>   This allows the preview to load resources like images and CSS from
>   the default Pandoc user data directory.

I'm not excited about setting extra resource roots automatically or setting them via environment variables, since that could make it harder to reason about security settings. However, these new settings should give you a lot of additional flexibility. For example, if you put your custom data dir inside the default Pandoc user data directory as a subdirectory, then all resources will now automatically be accessible by the preview. And you can access them in defaults files via `${USERDATA}/<subdir>/...`. If you are only working with trusted documents, you also have the option to set `~/` as a resource root, effectively disabling many of the security settings.

**Comment by wlupton** [comment]
Thanks very much!
