### ISSUE TITLE
use own css for vscode preview

### ISSUE THREAD

**Issue by hleiaa** [gpoore/codebraid-preview-vscode#19]
I might be missing something, but i cannot make the codebraid markdown preview support my preview css. Here is vscode's [documentation for preview css.](https://code.visualstudio.com/docs/languages/markdown#_using-your-own-css)

My codebraid setting:
- css override default: false
- css use default: true
- css markdown preview font settings: true (inherit)
- css custome data: `vscode_preview.css`

Above `vscode_preview.css` is the css file for this project, which is used by vscode built-in preview.

**Comment by gpoore** [comment]
The Codebraid Markdown preview does not use the settings from the built-in VS Code Markdown preview, so `markdown.styles` in settings has no effect. It might be possible to inherit some of the settings from the built-in preview in the future, but because the Codebraid preview is generated with Pandoc, inheriting all settings from the built-in preview isn't an option. Currently, modifying CSS is done by customizing the Pandoc build process.

To customize preview CSS for all documents, you want to go to `codebraid.preview.pandoc.build` in the VS Code settings. Under `*.md`, `preview.html.options`, you can add something like `--css vscode_preview.css`. Depending on where the CSS file is located, you may need to specify a path. If the path contains spaces, the path (or at least part) should be quoted, since this is used in a shell. `~` is expanded under all operating systems.

To customize preview CSS for a single document/directory, you can create a `_codebraid_preview.yml` file and then add an entry `css: vscode_preview.css`.

Also, you may want `codebraid.preview.css.overrideDefault` set to `true`.

**Comment by hleiaa** [comment]
Thanks for the detailed response. Creating a `_codebraid_preview.yml` file solves my problem.

**Comment by gpoore** [comment]
The development version now supports `markdown.styles`, and includes a new setting `codebraid.preview.css.useMarkdownPreviewStyles` that determines whether `markdown.styles` is used (default is true). A new release including this should be out in the next day or two.
