### ISSUE TITLE
Interaction with codebraid

### ISSUE THREAD

**Issue by memeplex** [gpoore/codebraid-preview-vscode#22]
Hi, just a question. It confuses me that this extension is named codebraid-preview. The documentation states that execution of code through codebraid is optional. Other than that, has this extension any dependency on codebraid? Should I install it even if I don't use the code execution feature? In any case, will be any overhead for codeless inputs? Thank you in advance.

**Comment by gpoore** [comment]
If you're just using the VS Code extension to preview Markdown documents or other formats, you don't need Codebraid installed. There is essentially no overhead related to Codebraid if you're not using code execution.

**Comment by memeplex** [comment]
Great, thanks!

**Comment by memeplex** [comment]
Just a remark. I think your extension is adding a lot of value by putting pandoc support on par with built-in markdown support. As a vehicle to codebraid it's perhaps more niche, but as a pandoc preview solution its potential audience is wider. I believe it deserves to be more well known, perhaps it's not clear to people that it's just the best previewing solution available for pandoc, because it sounds more as a tool for reproducible research from its name/description.

**Comment by gpoore** [comment]
That's a good point. I may need to reconsider some of the "branding" for the extension. It started off focused on Codebraid features with a preview for the commonmark_x format, but it has a lot more general Pandoc features now. Many of the current features weren't possible when I first started, since Pandoc's Lua filters hadn't yet become so powerful!
