### ISSUE TITLE
matplotlib plots are not rendering

### ISSUE THREAD

**Issue by mwcraig** [gpoore/codebraid-preview-vscode#6]
I'm using `codebraid-preview 0.5.1` with `codebraid 0.8`. When I run the short file below in a conda environment that includes matplotlib I do not get a plot in the output.

- Tested on M1 Mac, macOS 12.4
- Python and `codebraid` installed in a conda environment.
- Pandoc installed via homebrew

Screenshot of result:

<img width="1786" alt="no-plot_md" src="https://user-images.githubusercontent.com/1147167/174448650-cdb19ec2-c7dc-43f9-82fb-a4f5ce67561c.png">

Input file is attached:

[no-plot.md](https://github.com/gpoore/vscode-codebraid-preview/files/8933981/no-plot.md)

**Comment by gpoore** [comment]
I think this just needs to set a Jupyter kernel, so that plot display is automatic (instead of using the built-in code execution system). Only the first code chunk for a session needs to set the kernel. Probably something like this:
``````
```{.python .cb-nb jupyter_kernel=python3}
print('Hello world!')

import matplotlib.pyplot as plt

plt.plot([0, 1])
```
``````
I'm hoping to reorganize the documentation into a proper website soon, and as part of that I probably need to emphasize `jupyter_kernel` more. I'm also planning to add a single, document-wide option to make Jupyter the default for code execution, so that individual `jupyter_kernel` settings won't be required.

**Comment by mwcraig** [comment]
Thanks -- this worked after I installed `jupyter_client` and `ipykernel`!
